FROM unicef/etools-prp-base:base-312

ARG env
ENV ENV ${env:-dev}

# these packages are required
RUN apk add --no-cache --virtual --update \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    ttf-opensans

WORKDIR /etools/
ADD .pdm-python .
ADD pdm.lock .
ADD pyproject.toml .
RUN pdm sync

ENV PYTHONPATH=/etools/__pypackages__/3.12/lib

RUN CFLAGS="-I/usr/local/include/python3.12" UWSGI_PROFILE="asyncio"

RUN mkdir -p /data/django_api/logs
RUN mkdir -p /data/uploads
RUN touch /data/django_api/logs/django.log

RUN chmod -R a+rw /data

ENV PYTHONUNBUFFERED 1
WORKDIR /code/
