FROM python:3.7-alpine

ARG env
ENV ENV ${env:-dev}

RUN apk update
RUN apk add --upgrade apk-tools

RUN apk add openssl \
    ca-certificates \
    libressl3.0-libcrypto

RUN apk add libxslt \
    geos \
    gdal

RUN apk add postgresql-client

#### Build-deps
RUN apk add --no-cache --virtual .build-deps \
    --update alpine-sdk

RUN apk add --no-cache --virtual .build-deps1 \
    libxml2-dev \
    libxslt-dev \
    xmlsec-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    python-dev \
    git

RUN apk add --no-cache --virtual .build-deps2 \
    geos-dev \
    gdal-dev

RUN apk add --no-cache --virtual .build-deps3 \
    gcc \
    g++

# PYTHON
RUN pip install --no-cache-dir --upgrade \
    setuptools \
    pip

RUN mkdir -p /data/django_api/logs
RUN mkdir -p /data/uploads
RUN touch /data/django_api/logs/django.log

RUN chmod -R a+rw /data

ENV PYTHONUNBUFFERED 1
WORKDIR /code/
