# TODO change this to etools-base, if etools Dockerfile-base changes accepted
# See https://github.com/unicef/etools/pull/2716
FROM unicef/etools-prp-base:latest

ARG env
ENV ENV ${env:-dev}

# TODO remove this line once useing etools-prp
# See https://github.com/unicef/etools/pull/2716
RUN pip install --no-cache-dir --upgrade pipenv

WORKDIR /etools/
ADD Pipfile .
ADD Pipfile.lock .
RUN pipenv install --dev --system  --ignore-pipfile
RUN apk add bash

RUN pip install greenlet==0.4.14
RUN CFLAGS="-I/usr/local/include/python3.7" UWSGI_PROFILE="asyncio" pip install uwsgi==2.0.15

RUN mkdir -p /data/django_api/logs
RUN mkdir -p /data/uploads
RUN touch /data/django_api/logs/django.log

RUN chmod -R a+rw /data

ENV PYTHONUNBUFFERED 1
WORKDIR /code/
