FROM unicef/etools-prp-base:base-39

ARG env
ENV ENV ${env:-dev}

# these packages are required
RUN apk add --no-cache --virtual --update \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    ttf-opensans

WORKDIR /etools/
ADD Pipfile .
ADD Pipfile.lock .
RUN pipenv install --dev --system  --ignore-pipfile

RUN CFLAGS="-I/usr/local/include/python3.9" UWSGI_PROFILE="asyncio"

RUN mkdir -p /data/django_api/logs
RUN mkdir -p /data/uploads
RUN touch /data/django_api/logs/django.log

RUN chmod -R a+rw /data

ENV PYTHONUNBUFFERED 1
WORKDIR /code/
