# unicef/etools-prp-base:base-39
FROM python:3.9.6-alpine3.14

RUN apk update
RUN apk add --upgrade apk-tools \
    openssl \
    ca-certificates \
    libmagic \
    libxslt \
    geos \
    gdal \
    postgresql-client


# Build-deps
RUN apk add --no-cache --virtual .build-deps --update \
    alpine-sdk \
    libxml2-dev \
    libxslt-dev \
    xmlsec-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    geos-dev \
    gdal-dev \
    gcc \
    g++


# PYTHON
RUN pip install --no-cache-dir --upgrade \
    setuptools \
    pip \
    pipenv