# Dockerfile base

# unicef/etools-prp-base:base-39
FROM python:3.9.6-alpine3.14

RUN apk update

RUN apk add \
    --update alpine-sdk

RUN apk add --upgrade apk-tools \
    openssl \
    ca-certificates \
    libmagic \
    libxslt \
    geos \
    gdal \
    postgresql-client


# Build-deps
RUN apk add --no-cache --virtual .build-deps --update \
    alpine-sdk \
    libxml2-dev \
    libxslt-dev \
    xmlsec-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    geos-dev \
    gdal-dev \
    gcc \
    g++

RUN pip install --no-cache-dir --upgrade \
    pip \
    pipenv

# End Dockerfile base

# Dockerfile-installed

ARG env
ENV ENV ${env:-dev}

# these packages are required
RUN apk add --no-cache --virtual --update \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    ttf-opensans

WORKDIR /etools/
ADD Pipfile .
ADD Pipfile.lock .
RUN cat Pipfile.lock
RUN pipenv install --dev --system  --ignore-pipfile

RUN CFLAGS="-I/usr/local/include/python3.9" UWSGI_PROFILE="asyncio"

RUN mkdir -p /data/django_api/logs
RUN mkdir -p /data/uploads
RUN touch /data/django_api/logs/django.log

RUN chmod -R a+rw /data

ENV PYTHONUNBUFFERED 1
WORKDIR /code/

# End Dockerfile-installed


ARG env
ENV ENV ${env:-dev}

ADD . /code/

WORKDIR /code/
RUN apk add bash

# Patch drfpasswordless for Django 4.x compatibility
RUN python patch_drfpasswordless.py

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /code

RUN python manage.py collectstatic --noinput

RUN curl -o /usr/local/bin/waitforit -sSL https://github.com/maxcnunes/waitforit/releases/download/v2.2.0/waitforit-linux_amd64
RUN chmod +x /usr/local/bin/waitforit

EXPOSE 8000
