# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterobjective',
            name='reference_number',
        ),
    ]
