# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 23:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterobjective',
            name='locations',
            field=models.ManyToManyField(related_name='cluster_objectives', to='core.Location'),
        ),
        migrations.AddField(
            model_name='clusteractivity',
            name='cluster_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_activities', to='cluster.ClusterObjective'),
        ),
        migrations.AddField(
            model_name='clusteractivity',
            name='locations',
            field=models.ManyToManyField(related_name='cluster_activities', to='core.Location'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='response_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.ResponsePlan'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together=set([('type', 'response_plan')]),
        ),
    ]
