# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('cluster', '0002_auto_20170403_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_activities', to='cluster.Cluster')),
                ('cluster_objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_activities', to='cluster.ClusterObjective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_activities', to='reporting.Project')),
            ],
        ),
    ]
