# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170915_0223'),
        ('cluster', '0002_auto_20170915_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteractivity',
            name='locations',
            field=models.ManyToManyField(related_name='cluster_activities', to='core.Location'),
        ),
        migrations.AddField(
            model_name='clusterobjective',
            name='locations',
            field=models.ManyToManyField(related_name='cluster_objectives', to='core.Location'),
        ),
    ]
