# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20170601_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterobjective',
            name='frequency',
            field=models.CharField(choices=[('Wee', 'Weekly'), ('Mon', 'Monthly'), ('Qua', 'Quarterly')], default='Mon', max_length=3, verbose_name='Frequency of reporting'),
        ),
        migrations.AddField(
            model_name='clusterobjective',
            name='reference_number',
            field=models.CharField(default='draft ref no', max_length=255, verbose_name='Reference Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusterobjective',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Cluster Objective Title'),
        ),
    ]
