# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_remove_clusterobjective_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterobjective',
            name='frequency',
        ),
    ]
