# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-06 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20190522_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusteractivity',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Cluster activities'},
        ),
    ]
