# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20170529_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteractivity',
            name='frequency',
            field=models.CharField(choices=[('Wee', 'Weekly'), ('Mon', 'Monthly'), ('Qua', 'Quarterly')], default='Mon', max_length=3, verbose_name='Frequency of reporting'),
        ),
        migrations.AddField(
            model_name='clusteractivity',
            name='standard',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
