# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_remove_clusteractivity_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteractivity',
            name='standard',
        ),
    ]
