# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20170601_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusteractivity',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='clusterobjective',
            options={'ordering': ['-id']},
        ),
    ]
