# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20170704_1401'),
        ('cluster', '0005_auto_20170706_1830'),
    ]

    operations = [
    ]
