# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_auto_20180301_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='clusteractivity',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='clusterobjective',
            name='external_url',
        ),
    ]
