# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_auto_20171219_1939'),
        ('cluster', '0006_auto_20180313_1044'),
    ]

    operations = [
    ]
