# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_auto_20180305_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='imported_type',
            field=models.TextField(blank=True, help_text='Type as specified in the external system', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='type',
            field=models.CharField(choices=[('cccm', 'CCCM'), ('early_recovery', 'Early Recovery'), ('education', 'Education'), ('emergency_telecommunications', 'Emergency Telecommunications'), ('food_security', 'Food Security'), ('health', 'Health'), ('logistics', 'Logistics'), ('nutrition', 'Nutrition'), ('protection', 'Protection'), ('shelter', 'Shelter'), ('wash', 'WASH'), ('imported', 'Imported')], max_length=32),
        ),
    ]
