# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180305_2022'),
        ('cluster', '0008_auto_20180306_2035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together=set([('external_id', 'external_source'), ('type', 'imported_type', 'response_plan')]),
        ),
    ]
