# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170403_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.Partner'),
        ),
    ]
