# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171012_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imo_clusters',
            field=models.ManyToManyField(blank=True, help_text='These are the clusters this user will have IMO privileges over.', null=True, related_name='users', to='cluster.Cluster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(blank=True, help_text='These are workspaces that the user will be able to access.', null=True, related_name='users', to='core.Workspace'),
        ),
    ]
