# Generated by Django 1.11.11 on 2018-07-25 12:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
