# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171031_1159'),
        ('account', '0004_auto_20171031_0545'),
    ]

    operations = [
    ]
