# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20171102_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imo_clusters',
            field=models.ManyToManyField(blank=True, help_text='These are the clusters this user will have IMO privileges over.', related_name='users', to='cluster.Cluster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(blank=True, help_text='These are workspaces that the user will be able to access.', related_name='users', to='core.Workspace'),
        ),
    ]
