# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180306_0007'),
        ('account', '0007_auto_20180302_1156'),
    ]

    operations = [
    ]
