# Generated by Django 1.11.11 on 2018-09-17 13:56
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
