# Generated by Django 1.11.11 on 2018-10-24 23:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0003_auto_20181004_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
