# Generated by Django 1.11.15 on 2018-12-04 00:13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181024_0034'),
        ('unicef', '0004_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerleveloutput',
            name='external_business_area_code',
            field=models.CharField(blank=True, help_text='A Workspace business area code as unique constraint factor', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pdresultlink',
            name='external_business_area_code',
            field=models.CharField(blank=True, help_text='A Workspace business area code as unique constraint factor', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='external_business_area_code',
            field=models.CharField(blank=True, help_text='A Workspace business area code as unique constraint factor', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reportingperioddates',
            name='external_business_area_code',
            field=models.CharField(blank=True, help_text='A Workspace business area code as unique constraint factor', max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lowerleveloutput',
            unique_together=set([('external_id', 'external_business_area_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='pdresultlink',
            unique_together=set([('external_id', 'external_business_area_code', 'external_cp_output_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='programmedocument',
            unique_together=set([('external_id', 'external_business_area_code', 'workspace')]),
        ),
        migrations.AlterUniqueTogether(
            name='reportingperioddates',
            unique_together=set([('external_id', 'external_business_area_code', 'programme_document')]),
        ),
    ]
