# Generated by Django 1.11.20 on 2019-09-11 21:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0013_auto_20190903_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lowerleveloutput',
            unique_together=set([('external_id', 'external_business_area_code', 'cp_output')]),
        ),
    ]
