# Generated by Django 1.11.20 on 2019-09-20 17:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0014_auto_20190911_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SHP', 'Simplified Humanitarian Programme Document'), ('SSFA', 'SSFA TOR')], default='PD', max_length=4, verbose_name='Document Type'),
        ),
    ]
