# Generated by Django 1.11.20 on 2019-11-06 23:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0015_auto_20190920_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportingperioddates',
            options={'verbose_name_plural': 'Reporting period dates'},
        ),
    ]
