# Generated by Django 2.2.16 on 2020-11-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0018_auto_20200520_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportingperioddates',
            options={'ordering': ('-end_date',), 'verbose_name_plural': 'Reporting period dates'},
        ),
    ]
