# Generated by Django 3.2 on 2021-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0020_auto_20201119_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='amendments',
            field=models.JSONField(default=list),
        ),
    ]
