# Generated by Django 3.2.6 on 2021-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0020_auto_20201119_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='amendments',
            field=models.JSONField(default=list),
        ),
    ]
