# Generated by Django 3.2.6 on 2022-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0021_auto_20210924_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Not', 'Not Yet Due'), ('Ove', 'Overdue'), ('Sub', 'Submitted'), ('Sen', 'Sent back'), ('Acc', 'Accepted')], default='Due', max_length=3),
        ),
    ]
