# Generated by Django 3.2.6 on 2022-06-06 16:23

from django.db import migrations, models

NEW_PD_STATUSES = (
    ("draft", "development", "Development"),
    ("review", "review", "Review"),
    ("signature", "signature", "Signature"),
    ("signed", "signed", "Signed"),
    ("active", "active", "Active"),
    ("cancelled", "cancelled", "Cancelled"),
    ('ended', 'ended', 'Ended'),
    ('closed', 'closed', 'Closed'),
    ("suspended", "suspended", "Suspended"),
    ('terminated', 'terminated', 'Terminated'),
    ('expired', 'expired', 'Expired'),
)
PD_STATUS = [
    ("Dra", "draft"),
    ("Sig", "signed"),
    ("Act", "active"),
    ("Sus", "suspended"),
    ('End', 'ended'),
    ('Clo', 'closed'),
    ('Ter', 'terminated'),
]
PD_DOC_TYPE = [
        ('PD', 'PD'),
        ('SPD', 'SPD'),
        ('SHP', 'SPD'),
        ('HPD', 'SPD'),
        ('SSFA', 'SPD')
]
PD_STATUS_MAP = dict(PD_STATUS)
PD_DOC_TYPE_MAP = dict(PD_DOC_TYPE)
def migrate_status(apps, schema_editor):
    Intervention = apps.get_model('unicef', 'ProgrammeDocument')
    for i in Intervention.objects.all():
        i.status = PD_STATUS_MAP[i.status]
        i.document_type = PD_DOC_TYPE_MAP[i.document_type]
        i.save()


class Migration(migrations.Migration):


    dependencies = [
        ('unicef', '0021_auto_20210924_1700'),
    ]

    operations = [
        migrations.RunPython(migrate_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='programmedocument',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SPD', 'SPDProgramme Document'), ('SHP', 'Simplified Humanitarian Programme Document'), ('SSFA', 'SSFA')], default='PD', max_length=4, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Development'), ('review', 'Review'), ('signature', 'Signature'), ('signed', 'Signed'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=256, verbose_name='PD/SSFA status'),
        ),
    ]
