# Generated by Django 3.2.6 on 2022-03-16 15:39

from django.db import migrations, models
import etools_prp.apps.core.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0021_auto_20210924_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='amendments',
            field=models.JSONField(default=list, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
    ]
