# Generated by Django 3.2.15 on 2022-11-24 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0022_alter_progressreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('release_cash_in_time_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('release_cash_in_time_comment', models.TextField(blank=True, null=True, verbose_name='Did UNICEF release cash in time')),
                ('release_supplies_in_time_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('release_supplies_in_time_comment', models.TextField(blank=True, null=True, verbose_name='Did UNICEF release supplies in time')),
                ('feedback_face_form_in_time_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('feedback_face_form_in_time_comment', models.TextField(blank=True, null=True, verbose_name='Did UNICEF provide timely feedback on FACE forms')),
                ('respond_requests_in_time_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('respond_requests_in_time_comment', models.TextField(blank=True, null=True, verbose_name='Did UNICEF staff respond to queries and requests')),
                ('implemented_as_planned_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('implemented_as_planned_comment', models.TextField(blank=True, null=True, verbose_name='Were activities implemented as planned')),
                ('action_to_address_choice', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('action_to_address_comment', models.TextField(blank=True, null=True, verbose_name='Action to address findings')),
                ('overall_satisfaction_choice', models.CharField(blank=True, choices=[('very_unsatisfied', 'Very Unsatisfied'), ('unsatisfied', 'Unsatisfied'), ('neutral', 'Neutral'), ('satisfied', 'Satisfied'), ('very_satisfied', 'Very Satisfied')], max_length=20, null=True)),
                ('overall_satisfaction_comment', models.TextField(blank=True, null=True)),
                ('progress_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_review', to='unicef.progressreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
