# Generated by Django 3.2.6 on 2022-12-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0022_auto_20220606_1623'),
        ('unicef', '0023_finalreview'),
    ]

    operations = [
    ]
