# Generated by Django 3.2.15 on 2024-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0026_alter_programmedocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='accepted_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Report accepted comment'),
        ),
    ]
