# Generated by Django 3.2.15 on 2024-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0029_auto_20241206_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='has_signed_document',
            field=models.BooleanField(default=False),
        ),
    ]
