# Generated by Django 3.2.6 on 2025-06-05 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef', '0030_programmedocument_has_signed_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPDProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('partner_contribution_to_date', models.TextField(blank=True, null=True)),
                ('financial_contribution_to_date', models.TextField(blank=True, null=True)),
                ('financial_contribution_currency', models.CharField(choices=[('AED', 'aed'), ('AFN', 'afn'), ('ALL', 'all'), ('AMD', 'amd'), ('ANG', 'ang'), ('AOA', 'aoa'), ('ARS', 'ars'), ('AUD', 'aud'), ('AWG', 'awg'), ('AZN', 'azn'), ('BAM', 'bam'), ('BBD', 'bbd'), ('BDT', 'bdt'), ('BGN', 'bgn'), ('BHD', 'bhd'), ('BIF', 'bif'), ('BMD', 'bmd'), ('BND', 'bnd'), ('BOB', 'bob'), ('BRL', 'brl'), ('BSD', 'bsd'), ('BTN', 'btn'), ('BWP', 'bwp'), ('BYN', 'byn'), ('BZD', 'bzd'), ('CAD', 'cad'), ('CDF', 'cdf'), ('CHF', 'chf'), ('CLP', 'clp'), ('CNY', 'cny'), ('COP', 'cop'), ('CRC', 'crc'), ('CUC', 'cuc'), ('CUP', 'cup'), ('CVE', 'cve'), ('CZK', 'czk'), ('DJF', 'djf'), ('DKK', 'dkk'), ('DOP', 'dop'), ('DZD', 'dzd'), ('EGP', 'egp'), ('ERN', 'ern'), ('ETB', 'etb'), ('EUR', '€'), ('FJD', 'fjd'), ('FKP', 'fkp'), ('GBP', 'gbp'), ('GEL', 'gel'), ('GGP', 'ggp'), ('GHS', 'ghs'), ('GIP', 'gip'), ('GMD', 'gmd'), ('GNF', 'gnf'), ('GTQ', 'gtq'), ('GYD', 'gyd'), ('HKD', 'hkd'), ('HNL', 'hnl'), ('HRK', 'hrk'), ('HTG', 'htg'), ('HUF', 'huf'), ('IDR', 'idr'), ('ILS', 'ils'), ('IMP', 'imp'), ('INR', 'inr'), ('IQD', 'iqd'), ('IRR', 'irr'), ('ISK', 'isk'), ('JEP', 'jep'), ('JMD', 'jmd'), ('JOD', 'jod'), ('JPY', 'jpy'), ('KES', 'kes'), ('KGS', 'kgs'), ('KHR', 'khr'), ('KMF', 'kmf'), ('KPW', 'kpw'), ('KRW', 'krw'), ('KWD', 'kwd'), ('KYD', 'kyd'), ('KZT', 'kzt'), ('LAK', 'lak'), ('LBP', 'lbp'), ('LKR', 'lkr'), ('LRD', 'lrd'), ('LSL', 'lsl'), ('LYD', 'lyd'), ('MAD', 'mad'), ('MDL', 'mdl'), ('MGA', 'mga'), ('MKD', 'mkd'), ('MMK', 'mmk'), ('MNT', 'mnt'), ('MOP', 'mop'), ('MRO', 'mro'), ('MRU', 'mru'), ('MUR', 'mur'), ('MVR', 'mvr'), ('MWK', 'mwk'), ('MXN', 'mxn'), ('MYR', 'myr'), ('MZN', 'mzn'), ('NAD', 'nad'), ('NGN', 'ngn'), ('NIO', 'nio'), ('NOK', 'nok'), ('NPR', 'npr'), ('NZD', 'nzd'), ('OMR', 'omr'), ('PAB', 'pab'), ('PEN', 'pen'), ('PGK', 'pgk'), ('PHP', 'php'), ('PKR', 'pkr'), ('PLN', 'pln'), ('PYG', 'pyg'), ('QAR', 'qar'), ('RON', 'ron'), ('RSD', 'rsd'), ('RUB', 'rub'), ('RWF', 'rwf'), ('SAR', 'sar'), ('SBD', 'sbd'), ('SCR', 'scr'), ('SDG', 'sdg'), ('SEK', 'sek'), ('SGD', 'sgd'), ('SHP', 'shp'), ('SLE', 'sle'), ('SOS', 'sos'), ('SPL', 'spl'), ('SRD', 'srd'), ('STD', 'std'), ('SVC', 'svc'), ('SYP', 'syp'), ('SZL', 'szl'), ('THB', 'thb'), ('TJS', 'tjs'), ('TMT', 'tmt'), ('TND', 'tnd'), ('TOP', 'top'), ('TRY', 'try'), ('TTD', 'ttd'), ('TVD', 'tvd'), ('TWD', 'twd'), ('TZS', 'tzs'), ('UAH', 'uah'), ('UGX', 'ugx'), ('USD', '$'), ('UYU', 'uyu'), ('UZS', 'uzs'), ('VEF', 'vef'), ('VND', 'vnd'), ('VUV', 'vuv'), ('WST', 'wst'), ('XAF', 'xaf'), ('XCD', 'xcd'), ('XDR', 'xdr'), ('XOF', 'xof'), ('XPF', 'xpf'), ('YER', 'yer'), ('YER1', 'yer1'), ('ZAR', 'zar'), ('ZMW', 'zmw'), ('ZWD', 'zwd'), ('ZWL', 'zwl'), ('SSP', 'ssp')], default='USD', max_length=16, verbose_name='Financial Contribution Currency')),
                ('challenges_in_the_reporting_period', models.TextField(blank=True, null=True)),
                ('proposed_way_forward', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Not', 'Not Yet Due'), ('Ove', 'Overdue'), ('Sub', 'Submitted'), ('Sen', 'Sent back'), ('Acc', 'Accepted')], default='Due', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission Date')),
                ('delivered_as_planed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], default='yes', max_length=10)),
                ('results_achieved', models.CharField(blank=True, max_length=256, null=True)),
                ('answer_factor', models.CharField(blank=True, max_length=256, null=True)),
                ('other_information', models.CharField(blank=True, max_length=256, null=True)),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Review Date')),
                ('reviewed_by_email', models.CharField(blank=True, max_length=256, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=256, null=True)),
                ('reviewed_by_external_id', models.IntegerField(blank=True, null=True)),
                ('review_overall_status', models.CharField(blank=True, choices=[('Met', 'Met'), ('OnT', 'On Track'), ('NoP', 'No Progress'), ('Con', 'Constrained'), ('NoS', 'No Status')], max_length=3, null=True, verbose_name='Overall status set by UNICEF PO')),
                ('sent_back_feedback', models.TextField(blank=True, null=True)),
                ('accepted_comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Report accepted comment')),
                ('report_number', models.IntegerField(verbose_name='Report Number')),
                ('report_type', models.CharField(choices=[('QPR', 'Quarterly Progress Report'), ('HR', 'Humanitarian Report'), ('SR', 'Special Report')], max_length=3, verbose_name='Report type')),
                ('is_final', models.BooleanField(default=False, verbose_name='Is final report')),
                ('narrative', models.TextField(blank=True, null=True, verbose_name='Narrative')),
                ('programme_document', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='gpd_progress_reports', to='unicef.programmedocument')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted by / on behalf on')),
                ('submitting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpd_submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
                'unique_together': {('programme_document', 'report_type', 'report_number')},
            },
        ),
    ]
