# Generated by Django 3.2.15 on 2025-06-23 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0030_programmedocument_has_signed_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreview',
            name='progress_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_review', to='unicef.progressreport'),
        ),
        migrations.CreateModel(
            name='GPDProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('delivered_as_planned', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], max_length=10, null=True, verbose_name='Activities delivered as planned')),
                ('results_achieved', models.TextField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
                ('gpd_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpd_report', to='unicef.progressreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
