# Generated by Django 3.2.6 on 2025-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0031_auto_20250623_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Development'), ('review', 'Review'), ('signature', 'Signature'), ('signed', 'Signed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=256, verbose_name='PD/SPD status'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='title',
            field=models.CharField(db_index=True, max_length=512, verbose_name='PD/SPD ToR Title'),
        ),
    ]
