# Generated by Django 3.2.6 on 2025-06-18 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etools_prp.apps.unicef.models
import model_utils.fields

class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0031_auto_20250605_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpdprogressreport',
            name='delivered_as_planed',
        ),
        migrations.AddField(
            model_name='gpdprogressreport',
            name='delivered_as_planned',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], default='yes', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='GPDProgressReportAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('file',
                 models.FileField(max_length=500, upload_to=etools_prp.apps.unicef.models.get_pr_attachment_upload_to)),
                ('type', models.CharField(choices=[('FACE', 'FACE'), ('Other', 'Other')], max_length=5,
                                          verbose_name='Attachment type')),
                ('progress_report',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
                                   to='unicef.gpdprogressreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
