# Generated by Django 3.2.6 on 2025-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0031_auto_20250605_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpdprogressreport',
            name='delivered_as_planed',
        ),
        migrations.AddField(
            model_name='gpdprogressreport',
            name='delivered_as_planned',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], default='yes', max_length=10, null=True),
        ),
    ]
