FROM node:11.9.0-alpine
RUN apk update
RUN apk add --update bash

RUN apk add git
RUN npm install -g --unsafe-perm polymer-cli
RUN npm install -g gulp
RUN npm install -g typescript

WORKDIR /code

EXPOSE 8084
CMD ["npm", "run", "dev"]
