# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cso_type',
            field=models.CharField(blank=True, choices=[('Int', 'International'), ('Nat', 'National'), ('CBO', 'Community Based Organization'), ('AI', 'Academic Institution')], max_length=3, null=True, verbose_name='CSO Type'),
        ),
    ]
