# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='cluster',
            new_name='clusters',
        ),
        migrations.RenameField(
            model_name='partnerproject',
            old_name='cluster',
            new_name='clusters',
        ),
        migrations.RenameField(
            model_name='partnerproject',
            old_name='location',
            new_name='locations',
        ),
    ]
