# Generated by Django 1.11.11 on 2018-09-05 12:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerproject',
            unique_together=set([]),
        ),
    ]
