# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20171031_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneractivity',
            name='cluster_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_activities', to='cluster.ClusterActivity'),
        ),
        migrations.AlterField(
            model_name='partneractivity',
            name='cluster_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_activities', to='cluster.ClusterObjective'),
        ),
    ]
