# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20170511_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type_of_assessment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
