# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20170601_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerproject',
            name='additional_information',
            field=models.CharField(default='', max_length=255, verbose_name='Additional information (e.g. links)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='funding_source',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, help_text='Total Budget', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partnerproject',
            name='status',
            field=models.CharField(choices=[('Dra', 'Draft'), ('Act', 'Active'), ('Imp', 'Implemented'), ('Rej', 'Rejected')], default='Dra', max_length=3),
        ),
    ]
