# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20181024_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerActivityProjectContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Ong', 'Ongoing'), ('Pla', 'Planned'), ('Com', 'Completed')], default='Ong', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='partneractivity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='partneractivity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='partneractivity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='partneractivity',
            name='status',
        ),
        migrations.AlterField(
            model_name='partner',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
        migrations.AlterField(
            model_name='partnerproject',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
        migrations.AddField(
            model_name='partneractivityprojectcontext',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.PartnerActivity'),
        ),
        migrations.AddField(
            model_name='partneractivityprojectcontext',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.PartnerProject'),
        ),
        migrations.AddField(
            model_name='partneractivity',
            name='projects',
            field=models.ManyToManyField(related_name='partner_activities', through='partner.PartnerActivityProjectContext', to='partner.PartnerProject'),
        ),
        migrations.AlterUniqueTogether(
            name='partneractivityprojectcontext',
            unique_together=set([('project', 'activity')]),
        ),
    ]
