# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('partner', '0005_auto_20180226'), ('partner', '0006_auto_20180227_0823')]

    dependencies = [
        ('partner', '0004_auto_20180227_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerproject',
            name='funding_source',
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='external_source',
            field=models.TextField(blank=True, choices=[('RPM', 'RPM')], null=True),
        ),
    ]
