# Generated by Django 1.11.20 on 2019-11-06 23:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20190522_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneractivity',
            options={'ordering': ['-id'], 'permissions': (('imo_object', 'IMO Object'), ('partner_object', 'Partner Object')), 'verbose_name_plural': 'Partner activities'},
        ),
    ]
