# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_remove_partnerproject_budget'),
        ('partner', '0004_auto_20170522_2055'),
    ]

    operations = [
    ]
