# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20180306_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='basis_for_risk_rating',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
