# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20170706_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='status',
            field=models.CharField(choices=[('Ong', 'Ongoing'), ('Pla', 'Planned'), ('Com', 'Completed')], default='Ong', max_length=3),
        ),
    ]
