# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20170601_0151'),
        ('partner', '0005_merge_20170525_2035'),
    ]

    operations = [
    ]
