# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20180228_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
