# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170707_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneractivity',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='partnerproject',
            options={'ordering': ['-id']},
        ),
    ]
