# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20180302_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingsource',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='partnerproject',
            name='external_url',
        ),
    ]
