# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20180305_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='USD Amount'),
        ),
    ]
