# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_auto_20170807_2147'),
        ('partner', '0007_auto_20170807_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneractivity',
            name='cluster_objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_activities', to='cluster.ClusterObjective'),
        ),
    ]
