# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20180320_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='organization_type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
