# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20180305_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneractivity',
            options={'ordering': ['-id'], 'permissions': (('imo_object', 'IMO Object'), ('partner_object', 'Partner Object'))},
        ),
        migrations.AlterModelOptions(
            name='partnerproject',
            options={'ordering': ['-id'], 'permissions': (('imo_object', 'IMO Object'), ('partner_object', 'Partner Object'))},
        ),
    ]
