# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20180306_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='partnerproject',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
