# Generated by Django 2.2.16 on 2020-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20200630_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Project code in HRP'),
        ),
    ]
