# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20180321_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='additional_information',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional information (e.g. links)'),
        ),
    ]
