# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20180404_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProjectFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('required_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('internal_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('cerf_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Central Emergency Response Fund funding')),
                ('cbpf_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Country based pooled funds funding')),
                ('bilateral_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Funding from bilateral agreements, not including UNICEF/WFP')),
                ('unicef_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Funding from UNICEF including supplies cost')),
                ('wfp_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Funding from WFP including supplies cost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='additional_partners',
            field=models.ManyToManyField(blank=True, to='partner.Partner', verbose_name='Additional implementing partners'),
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='agency_name',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='agency_type',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='partnerproject',
            name='prioritization',
            field=models.TextField(blank=True, null=True, verbose_name='Prioritization Classification'),
        ),
        migrations.AlterField(
            model_name='partnerproject',
            name='code',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Project code in HRP'),
        ),
        migrations.AddField(
            model_name='partnerprojectfunding',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.PartnerProject'),
        ),
    ]
