# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20180406_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerproject',
            name='type',
            field=models.CharField(blank=True, choices=[('HRP', 'HRP'), ('FA', 'FA')], help_text='Is this project part of an HRP or FA?', max_length=3, null=True, verbose_name='Plan Type'),
        ),
    ]
