# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_partnerproject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerproject',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
