# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_partnerproject_custom_fields'),
        ('partner', '0013_merge_20180405_1232'),
    ]

    operations = [
    ]
