# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_partnerproject_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneractivity',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
