# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20180419_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='basis_for_risk_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Risk Rating'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_of_assessment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
