# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_merge_20180417_1213'),
        ('partner', '0017_auto_20180423_0830'),
    ]

    operations = [
    ]
