# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_merge_20180424_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneractivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='partnerproject',
            name='created_by',
        ),
    ]
