# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 10:31
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_merge_20180424_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneractivity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='partnerproject',
            name='created_by',
        ),
        migrations.AddField(
            model_name='partner',
            name='ocha_external_id',
            field=core.fields.UniqueNullCharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
