# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_partner_ocha_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='type_of_assessment',
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
