# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-26 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0021_auto_20180525_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerproject',
            unique_together=set([]),
        ),
    ]
