# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_clusteractivity'),
        ('activity', '0002_auto_20170403_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneractivity',
            name='cluster_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_activities', to='cluster.ClusterActivity'),
            preserve_default=False,
        ),
    ]
