# Generated by Django 1.11.11 on 2018-07-17 19:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180711_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workspaces',
        ),
    ]
