# Generated by Django 3.2.15 on 2022-11-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_cartodbtable'),
        ('account', '0004_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.workspace'),
        ),
    ]
