from django.urls import re_path

from .views import (
    ClusterActivityAPIView,
    ClusterActivityListAPIView,
    ClusterAnalysisIndicatorDetailsAPIView,
    ClusterAnalysisIndicatorsListAPIView,
    ClusterIndicatorsListExcelExportForAnalysisView,
    ClusterIndicatorsListExcelExportView,
    ClusterIndicatorsListExcelImportView,
    ClusterIndicatorsLocationListAPIView,
    ClusterListAPIView,
    ClusterObjectiveAPIView,
    ClusterObjectiveListCreateAPIView,
    ClusterReportablesIdListAPIView,
    IndicatorReportDetailAPIView,
    IndicatorReportsListAPIView,
    OperationalPresenceAggregationDataAPIView,
    OperationalPresenceLocationListAPIView,
    PartnerAnalysisIndicatorResultAPIView,
    PartnerAnalysisSummaryAPIView,
    ResponsePlanClusterDashboardAPIView,
    ResponsePlanPartnerDashboardAPIView,
)

urlpatterns = [
    re_path(r'^cluster-list/(?P<response_plan_id>\d+)/$', ClusterListAPIView.as_view(), name="cluster-list"),
    re_path(r'^cluster-objective/$', ClusterObjectiveAPIView.as_view(), name="cluster-objective"),
    re_path(r'^cluster-objective/(?P<pk>\d+)/$', ClusterObjectiveAPIView.as_view(), name="cluster-objective"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-objective-list/$',
            ClusterObjectiveListCreateAPIView.as_view(),
            name="cluster-objective-list"),
    re_path(r'^cluster-activity/(?P<pk>\d+)/$', ClusterActivityAPIView.as_view(), name="cluster-activity"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-activity-list/$',
            ClusterActivityListAPIView.as_view(),
            name="cluster-activity-list"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicator-reports/$',
            IndicatorReportsListAPIView.as_view(),
            name="cluster-indicator-reports-list"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicator-reports/(?P<pk>\d+)/$',
            IndicatorReportDetailAPIView.as_view(),
            name="cluster-indicator-reports-detail"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-reportable-simple-list/$',
            ClusterReportablesIdListAPIView.as_view(),
            name="cluster-reportable-simple-list"),
    re_path(r'^(?P<response_plan_id>\d+)/cluster-simple-list/$',
            ClusterListAPIView.as_view(),
            name="cluster-simple-list"),

    re_path(r'^(?P<response_plan_id>\d+)/cluster-dashboard/$',
            ResponsePlanClusterDashboardAPIView.as_view(),
            name="response-plan-cluster-dashboard"),
    re_path(r'^(?P<response_plan_id>\d+)/partner-dashboard/$',
            ResponsePlanPartnerDashboardAPIView.as_view(),
            name="response-plan-partner-dashboard"),

    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicator-reports/import/$',
            ClusterIndicatorsListExcelImportView.as_view(),
            name="cluster-indicators-list-excel-import"),

    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicator-reports/export/$',
            ClusterIndicatorsListExcelExportView.as_view(),
            name="cluster-indicators-list-excel"),

    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicator-reports/export-for-analysis/$',
            ClusterIndicatorsListExcelExportForAnalysisView.as_view(),
            name="cluster-indicators-list-excel-for-analysis"),

    re_path(r'^(?P<response_plan_id>\d+)/cluster-indicators-locations/$',
            ClusterIndicatorsLocationListAPIView.as_view(),
            name="cluster-indicators-locations"),

    re_path(r'^partner-analysis/$',
            PartnerAnalysisSummaryAPIView.as_view(),
            name="partner-analysis-summary"),

    re_path(r'^partner-analysis/response-plan/(?P<response_plan_id>\d+)/indicator/(?P<reportable_id>\d+)$',
            PartnerAnalysisIndicatorResultAPIView.as_view(),
            name="partner-analysis-indicator-result"),

    re_path(r'^cluster-analysis/(?P<response_plan_id>\d+)/operational-presence/map$',
            OperationalPresenceLocationListAPIView.as_view(),
            name="cluster-analysis-operational-presence-ma"),

    re_path(r'^cluster-analysis/(?P<response_plan_id>\d+)/operational-presence/data$',
            OperationalPresenceAggregationDataAPIView.as_view(),
            name="cluster-analysis-operational-presence-aggregation-data"),

    re_path(r'^cluster-analysis/(?P<response_plan_id>\d+)/indicators/$',
            ClusterAnalysisIndicatorsListAPIView.as_view(),
            name="cluster-analysis-indicators-list"),

    re_path(r'^cluster-analysis/(?P<response_plan_id>\d+)/indicators/(?P<reportable_id>\d+)$',
            ClusterAnalysisIndicatorDetailsAPIView.as_view(),
            name="cluster-analysis-indicators-detail"),
]
