# Generated by Django 3.2.6 on 2025-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20191217_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='clusteractivity',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='clusterobjective',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
    ]
