# Generated by Django 1.11.11 on 2018-10-24 00:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20180905_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='type',
            field=models.CharField(blank=True, choices=[('HRP', 'HRP'), ('FA', 'FA'), ('OTHER', 'Other')], help_text='Is this project part of an HRP or FA?', max_length=3, null=True, verbose_name='Plan Type'),
        ),
    ]
