# Generated by Django 1.11.20 on 2019-11-08 22:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20191106_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='custom_fields',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
