# Generated by Django 2.2.12 on 2020-05-20 18:33

from django.db import migrations
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20191108_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
