# Generated by Django 2.2.12 on 2020-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20200609_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='highest_risk_rating_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Highest Risk Rating Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='highest_risk_rating_type',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Highest Risk Rating Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='type_of_assessment',
            field=models.CharField(max_length=50, null=True, verbose_name='Assessment Type'),
        ),
    ]
