# Generated by Django 3.2.15 on 2022-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_alter_partnerproject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cso_type',
            field=models.CharField(blank=True, choices=[('Int', 'International'), ('Nat', 'National'), ('CBO', 'Community Based Organization'), ('AI', 'Academic Institution'), ('RC', 'Red Cross/Red Crescent National Societies')], max_length=3, null=True, verbose_name='CSO Type'),
        ),
    ]
