# Generated by Django 3.2.6 on 2022-03-16 15:39

from django.db import migrations, models
import etools_prp.apps.core.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_alter_partnerproject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder, null=True),
        ),
    ]
