# Generated by Django 3.2.6 on 2021-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_alter_partnerproject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerproject',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
