# Generated by Django 3.2.6 on 2025-06-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20250605_0657'),
        ('partner', '0012_auto_20250605_1017'),
    ]

    operations = [
    ]
