# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 18:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('unicef', '0001_initial'),
        ('cluster', '0002_auto_20170601_1853'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=1024)),
                ('unit', models.CharField(choices=[('number', 'number'), ('percentage', 'percentage'), ('yesno', 'yesno')], default='number', max_length=10)),
                ('description', models.CharField(blank=True, max_length=3072, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True)),
                ('disaggregatable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorDataSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('calculation_method', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorDisaggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('range', django.contrib.postgres.fields.ranges.FloatRangeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorLocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('disaggregation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('time_period_start', models.DateField(auto_now=True)),
                ('time_period_end', models.DateField()),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report_status', models.CharField(choices=[('OT', 'On Track'), ('Con', 'Constrained'), ('NP', 'No Progress'), ('TM', 'Target Met')], default='OT', max_length=3)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_report', to='core.Location')),
                ('progress_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='unicef.ProgressReport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
                ('assumptions', models.TextField(blank=True, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cluster_indicator', models.BooleanField(default=False)),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Total')),
                ('disaggregation_logic', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('context_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code in current context')),
                ('object_id', models.PositiveIntegerField()),
                ('blueprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='indicator.IndicatorBlueprint')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('objective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='cluster.ClusterObjective')),
                ('parent_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indicator.Reportable')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='partner.PartnerProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='reportable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='indicator.Reportable'),
        ),
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='indicator_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_location_data', to='indicator.IndicatorReport'),
        ),
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_location_data', to='core.Location'),
        ),
        migrations.AddField(
            model_name='indicatordisaggregation',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_disaggregations', to='indicator.Reportable'),
        ),
        migrations.AddField(
            model_name='indicatordataspecification',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_specifications', to='indicator.Reportable'),
        ),
    ]
