# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_location_reportable'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='locations',
            field=models.ManyToManyField(related_name='reportables', to='core.Location'),
        ),
    ]
