# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='is_cluster_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
