# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0006_auto_20170517_1128'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='programme_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unicef.ProgrammeDocument'),
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='time_period',
            field=models.DateField(auto_now=True),
        ),
    ]
