# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_reportable_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Review Date'),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='sent_back_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
