# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20170517_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorreport',
            name='programme_document',
        ),
    ]
