# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20170601_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='frequency',
            field=models.CharField(choices=[('Wee', 'Weekly'), ('Mon', 'Monthly'), ('Qua', 'Quarterly')], default='Mon', max_length=3, verbose_name='Frequency of reporting'),
        ),
    ]
