# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20171110_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='in_need',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
