# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20190507_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregation',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF')], null=True),
        ),
    ]
