# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 04:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_reportable_in_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportable',
            name='cs_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, null=True, size=None),
        ),
    ]
