# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20170524_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='due_date',
            field=models.DateField(default=datetime.date(2017, 5, 25)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of submission'),
        ),
    ]
