# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20170927_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='title',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
