# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20170524_2139'),
        ('indicator', '0002_reportable_is_cluster_indicator'),
    ]

    operations = [
    ]
