# Generated by Django 1.11.20 on 2019-06-04 05:38
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20190522_1759'),
        ('indicator', '0004_auto_20190522_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='partner.PartnerProject'),
        ),
    ]
