# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_auto_20180227_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportable',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reportable',
            name='start_date',
        ),
    ]
