# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_merge_20170524_2235'),
        ('indicator', '0003_auto_20170522_2055'),
    ]

    operations = [
    ]
