# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_merge_20170524_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorblueprint',
            name='cluster_activity',
        ),
    ]
