# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-06 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_indicatorreport_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorlocationdata',
            options={'ordering': ['id'], 'verbose_name_plural': 'Indicator location data'},
        ),
        migrations.AlterModelOptions(
            name='reportingentity',
            options={'ordering': ['id'], 'verbose_name_plural': 'Reporting entities'},
        ),
    ]
