# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_merge_20170524_2235'),
        ('indicator', '0005_auto_20170525_1013'),
    ]

    operations = [
    ]
