# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20180305_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS')], null=True),
        ),
        migrations.AddField(
            model_name='indicatorblueprint',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS')], null=True),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='title',
            field=models.TextField(db_index=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='start_date',
            field=models.DateField(),
        ),
    ]
