# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_remove_indicatorreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorreport',
            name='report_status',
            field=models.CharField(choices=[('Ove', 'Overdue'), ('Sub', 'Submitted'), ('Acc', 'Accepted'), ('Sen', 'Sent back to partner'), ('Due', 'Due'), ('Not', 'Nothing due')], default='Due', max_length=3),
        ),
    ]
