# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20180314_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_locations',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('sum', 'sum')], default='sum', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_periods',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('sum', 'sum')], default='sum', max_length=10),
        ),
    ]
