# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 17:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_auto_20170531_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='location_progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='previous_location_progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
