# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_auto_20180322_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='comments',
            field=models.TextField(blank=True, max_length=4048, null=True),
        ),
        migrations.AddField(
            model_name='reportable',
            name='denominator_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='reportable',
            name='label',
            field=models.TextField(blank=True, max_length=4048, null=True),
        ),
        migrations.AddField(
            model_name='reportable',
            name='measurement_specifications',
            field=models.TextField(blank=True, max_length=4048, null=True),
        ),
        migrations.AddField(
            model_name='reportable',
            name='numerator_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='reportable',
            name='start_date_of_reporting_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_locations',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg')], default='sum', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_periods',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg')], default='sum', max_length=10),
        ),
    ]
