# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20170620_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='calculation_formula',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('min', 'min')], default='sum', max_length=3),
        ),
    ]
