# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 17:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20180326_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportable',
            name='in_need',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='in_need',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'d': 1, 'v': 0}, null=True),
        ),
    ]
