# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20170620_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='narrative_assessemnt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='overall_status',
            field=models.CharField(choices=[('Met', 'Met'), ('OnT', 'On Track'), ('NoP', 'No Progress'), ('Con', 'Constrained')], default='OnT', max_length=3),
        ),
    ]
