# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_indicatorreport_calculation_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorblueprint',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorlocationdata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorreport',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reportable',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='indicatorblueprint',
            name='display_type',
            field=models.CharField(choices=[('number', 'number'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='number', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='unit',
            field=models.CharField(choices=[('number', 'number'), ('percentage', 'percentage')], default='number', max_length=10),
        ),
    ]
