# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20170603_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorblueprint',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorlocationdata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorreport',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reportable',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='indicatorreport',
            old_name='narrative_assessemnt',
            new_name='narrative_assessment',
        ),
    ]
