# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20180403_1029'),
        ('indicator', '0012_auto_20180328_1752'),
    ]

    operations = [
    ]
