# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_auto_20170706_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorreport',
            name='calculation_formula',
        ),
    ]
