# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180313_1046'),
        ('indicator', '0013_merge_20180404_0725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportablelocationgoal',
            unique_together=set([('reportable', 'location')]),
        ),
    ]
