# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_reportable_created_by'),
        ('indicator', '0013_merge_20180404_0725'),
    ]

    operations = [
    ]
