# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_remove_indicatorreport_calculation_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorblueprint',
            old_name='calculation_formula',
            new_name='calculation_formula_across_locations',
        ),
        migrations.AddField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_periods',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10),
        ),
    ]
