# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_auto_20180405_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='title',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterUniqueTogether(
            name='disaggregationvalue',
            unique_together=set([('disaggregation', 'value')]),
        ),
    ]
