# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 01:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_auto_20180405_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='in_need',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
