# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0015_auto_20180407_0123'),
        ('indicator', '0015_auto_20180409_1018'),
    ]

    operations = [
    ]
