# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_auto_20170704_1401'),
        ('indicator', '0015_auto_20170706_2350'),
    ]

    operations = [
    ]
