# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0016_merge_20180409_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorblueprint',
            unique_together=set([('external_id', 'external_source')]),
        ),
    ]
