# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_merge_20180405_1232'),
        ('indicator', '0016_merge_20180409_1032'),
    ]

    operations = [
    ]
