# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0017_merge_20180411_1324'),
        ('indicator', '0017_auto_20180419_0805'),
    ]

    operations = [
    ]
