# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0017_auto_20180419_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indicator.IndicatorReport'),
        ),
        migrations.AddField(
            model_name='reportable',
            name='ca_indicator_used_by_reporting_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_indicators_re', to='indicator.Reportable'),
        ),
        migrations.AddField(
            model_name='reportingentity',
            name='indicator_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_entities', to='indicator.IndicatorReport'),
        ),
    ]
