# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0018_auto_20180424_2306'),
        ('indicator', '0018_merge_20180424_0951'),
    ]

    operations = [
    ]
