# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0019_auto_20170725_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='value',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
