# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0020_auto_20170801_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorblueprint',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorreport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reportable',
            options={'ordering': ['-id']},
        ),
    ]
