# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0019_merge_20180427_2126'),
        ('indicator', '0020_remove_reportable_created_by'),
    ]

    operations = [
    ]
