# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0021_merge_20180427_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingentity',
            name='indicator_report',
        ),
        migrations.AddField(
            model_name='reportingentity',
            name='title',
            field=models.CharField(default="UNICEF", max_length=256),
            preserve_default=False,
        ),
    ]
