# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 05:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0021_auto_20170807_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='location_admin_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
