# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0022_reportable_location_admin_refs'),
        ('indicator', '0022_merge_20170817_1416'),
    ]

    operations = [
    ]
