# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0022_auto_20180427_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='reporting_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='indicator.ReportingEntity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportingentity',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
