# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0023_auto_20180427_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='percentage_allocated',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Entered data value allocation by %', max_digits=5),
        ),
    ]
