# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0024_indicatorlocationdata_percentage_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorlocationdata',
            name='percentage_allocated',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Entered data value allocation by %', max_digits=5),
        ),
    ]
