# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0024_indicatorlocationdata_percentage_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='reporting_entity_percentage_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
