# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0025_auto_20180501_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='is_unicef_hf_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
