# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0026_reportable_is_unicef_hf_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorlocationdata',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
