# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 01:22
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document_type', models.CharField(blank=True, choices=[('PD', 'Programme Document'), ('SHP', 'Simplified Humanitarian Programme Document'), ('SSF', 'SSFA TOR')], max_length=255, null=True, verbose_name='Document type')),
                ('number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Dra', 'Draft'), ('Act', 'Active'), ('Imp', 'Implemented'), ('Sus', 'Suspended'), ('Ter', 'Terminated'), ('Can', 'Cancelled')], default='Dra', help_text='\n            Draft = In discussion with partner, Active = Currently ongoing,\n            Implemented = completed, Terminated = cancelled or not approved\n        ', max_length=3)),
                ('start', models.DateField(blank=True, help_text='The date the Intervention will start', null=True)),
                ('end', models.DateField(blank=True, help_text='The date the Intervention will end', null=True)),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('p_code', models.CharField(blank=True, max_length=32, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Location')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
