# Generated by Django 1.11.11 on 2018-08-23 11:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prprole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
