# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='carto_db_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.CartoDBTable'),
        ),
    ]
