# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170511_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modified',
        ),
    ]
