# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170601_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Response Plan')),
                ('plan_type', models.CharField(choices=[('HRP', 'HRP'), ('FA', 'FA')], default='HRP', max_length=3, verbose_name='Plan Type')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_plans', to='core.Intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
