# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180228_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='responseplan',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='external_url',
        ),
    ]
