# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170601_1830'),
        ('core', '0003_responseplan'),
    ]

    operations = [
    ]
