# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170920_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='reportable',
        ),
    ]
