# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170509_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(blank=True, choices=[('Dra', 'Draft'), ('Act', 'Active'), ('Imp', 'Implemented'), ('Sus', 'Suspended'), ('Ter', 'Terminated'), ('Can', 'Cancelled')], default='Dra', help_text='\n        Draft = In discussion with partner, Active = Currently ongoing,\n        Implemented = completed, Terminated = cancelled or not approved\n    ', max_length=3),
        ),
    ]
