# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181024_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
