# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180305_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS')], null=True),
        ),
    ]
