# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_workspace_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='workspace_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='responseplan',
            unique_together=set([('title', 'plan_type', 'workspace')]),
        ),
    ]
