# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 21:17
from __future__ import unicode_literals

import core.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import paintstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170807_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoDBTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=254)),
                ('api_key', models.CharField(max_length=254)),
                ('table_name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('name_col', models.CharField(default='name', max_length=254)),
                ('pcode_col', models.CharField(default='pcode', max_length=254)),
                ('parent_code_col', models.CharField(blank=True, max_length=254, null=True)),
                ('color', paintstore.fields.ColorPickerField(blank=True, default=core.models.get_random_color, max_length=7, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Location Type',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GatewayType'),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.CartoDBTable'),
        ),
        migrations.AddField(
            model_name='location',
            name='gateway',
            field=models.ForeignKey(default='Gateway 1', on_delete=django.db.models.deletion.CASCADE, to='core.GatewayType', verbose_name='Location Type'),
            preserve_default=False,
        ),
    ]
