# Generated by Django 1.11.20 on 2019-08-05 21:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190522_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaytype',
            name='display_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Display Name'),
        ),
    ]
