# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170817_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartodbtable',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='name_col',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='parent_code_col',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='pcode_col',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='locations',
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='intervention',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='carto_db_tables', to='core.Intervention'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatewaytype',
            name='intervention',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_types', to='core.Intervention'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='carto_db_table',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.CartoDBTable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='intervention',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.Intervention'),
            preserve_default=False,
        ),
    ]
