# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170515_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='locations',
            field=models.ManyToManyField(to='core.Location'),
        ),
    ]
