# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location_external_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='p_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Postal Code'),
        ),
    ]
