# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-06 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0004_auto_20191106_2329'),
        ('core', '0006_gatewaytype_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartodbtable',
            options={'verbose_name_plural': 'CartoDB tables'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='gatewaytype',
            options={'ordering': ['name'], 'verbose_name': 'Location type'},
        ),
        migrations.AlterModelOptions(
            name='prprole',
            options={'verbose_name_plural': 'PRP roles'},
        ),
        migrations.AlterUniqueTogether(
            name='prprole',
            unique_together=set([('user', 'role', 'workspace', 'cluster')]),
        ),
    ]
