# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180723_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartodbtable',
            name='api_key',
        ),
    ]
