# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_intervention_locations'),
        ('core', '0006_auto_20170524_1300'),
    ]

    operations = [
    ]
