# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cartodbtable_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_id',
            field=models.CharField(blank=True, help_text='An ID representing this instance in an external system', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('title', 'p_code'), ('external_id', 'external_source')]),
        ),
    ]
