# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20170817_1416'),
        ('core', '0007_gatewaytype_admin_level'),
    ]

    operations = [
    ]
