# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cartodbtable_api_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gatewaytype',
            unique_together=set([]),
        ),
    ]
