# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gatewaytype_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartodbtable',
            name='username',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
