# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-26 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180725_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('title', 'p_code')]),
        ),
    ]
