# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180726_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaytype',
            name='admin_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Admin Level'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gatewaytype',
            unique_together=set([('country', 'admin_level')]),
        ),
    ]
