# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='sent_back_date',
        ),
        migrations.AddField(
            model_name='progressreport',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Review Date'),
        ),
    ]
