# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='budget_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac'), ('JOD', 'JOD')], default='USD', max_length=16, verbose_name='Budget Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='cso_contribution_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac'), ('JOD', 'JOD')], default='USD', max_length=16, verbose_name='CSO Contribution Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='funds_received_to_date_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac'), ('JOD', 'JOD')], default='USD', max_length=16, verbose_name='Funds received Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='in_kind_amount_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac'), ('JOD', 'JOD')], default='USD', max_length=16, verbose_name='UNICEF Supplies Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='total_unicef_cash_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac'), ('JOD', 'JOD')], default='USD', max_length=16, verbose_name='UNICEF cash Currency'),
        ),
    ]
