# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from core.models import Workspace


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170915_0223'),
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='workspace',
            field=models.ForeignKey(default=Workspace.objects.first().id, on_delete=django.db.models.deletion.CASCADE, to='core.Workspace'),
            preserve_default=False,
        ),
    ]
