# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='ref',
            field=models.CharField(default='2017/', max_length=16),
            preserve_default=False,
        ),
    ]
