# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='agreement',
            field=models.CharField(default=None, max_length=255, verbose_name='Agreement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='population_focus',
            field=models.CharField(default=None, max_length=256, verbose_name='Population Focus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='reference_number',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='response_to_HRP',
            field=models.CharField(default=None, max_length=256, verbose_name='In response to an HRP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='status',
            field=models.CharField(default=None, max_length=256, verbose_name='PD/SSFA status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='PD/SSFA ToR Title'),
        ),
    ]
