# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0002_progressreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='programme_document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='unicef.ProgrammeDocument'),
            preserve_default=False,
        ),
    ]
