# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0002_auto_20170516_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='population_focus',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Population Focus'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='response_to_HRP',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='In response to an HRP'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='PD/SSFA status'),
        ),
    ]
