# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0003_auto_20170925_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriodDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='cs_dates',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='funds_received_to_date',
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='funds_received_to_date',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Funds received'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='funds_received_to_date_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', 'E')], default='USD', max_length=16, verbose_name='Funds received Currency'),
        ),
        migrations.AddField(
            model_name='reportingperioddates',
            name='programme_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='unicef.ProgrammeDocument'),
        ),
    ]
