# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0003_auto_20170528_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='cso_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CSO Contribution'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='in_kind_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='UNICEF Supplies'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='unicef_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='UNICEF cash'),
        ),
    ]
