# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170516_0927'),
        ('cluster', '0002_auto_20170511_0122'),
        ('unicef', '0003_auto_20170516_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='administrative_level',
            field=models.CharField(choices=[('Cou', 'Country level'), ('Reg', 'Region level'), ('Cit', 'City level')], default='Cou', max_length=3, verbose_name='Locations - administrative level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='cluster_leds',
            field=models.ManyToManyField(help_text='Select Cluster involved in program.', to='cluster.Cluster'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='contributing_to_cluser',
            field=models.BooleanField(default=True, verbose_name='Contributing to Cluser'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='locations',
            field=models.ManyToManyField(help_text='Select Administrative location for chosen level', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='population_focus',
            field=models.CharField(max_length=256, verbose_name='Population Focus'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='status',
            field=models.CharField(max_length=256, verbose_name='PD/SSFA status'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='sections',
            field=models.ManyToManyField(to='unicef.Section'),
        ),
    ]
