# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0003_auto_20170528_2133'),
        ('unicef', '0004_auto_20170528_2022'),
    ]

    operations = [
    ]
