# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0004_auto_20170926_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='budget_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac')], default='USD', max_length=16, verbose_name='Budget Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='cso_contribution_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac')], default='USD', max_length=16, verbose_name='CSO Contribution Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='funds_received_to_date_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac')], default='USD', max_length=16, verbose_name='Funds received Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='in_kind_amount_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac')], default='USD', max_length=16, verbose_name='UNICEF Supplies Currency'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='reference_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='PD/SSFA ToR Title'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='total_unicef_cash_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '\u20ac')], default='USD', max_length=16, verbose_name='UNICEF cash Currency'),
        ),
    ]
