# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0004_auto_20170516_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='frequency',
            field=models.CharField(choices=[('Wee', 'Weekly'), ('Mon', 'Monthly')], default='Mon', max_length=3, verbose_name='Frequency of reporting'),
        ),
    ]
