# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0004_auto_20170528_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmedocument',
            old_name='unicef_cash',
            new_name='total_unicef_cash',
        ),
    ]
