# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unicef.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0005_auto_20170528_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='programme_document',
            field=models.ForeignKey(default=unicef.models.find_first_programme_document_id, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='unicef.ProgrammeDocument'),
        ),
    ]
