# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0005_auto_20170929_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressreport',
            options={'ordering': ['-due_date', '-id']},
        ),
    ]
