# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0006_progressreport_programme_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryprogrammeoutput',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lowerleveloutput',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='programmedocument',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='progressreport',
            options={'ordering': ['id']},
        ),
    ]
