# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0006_auto_20171001_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='review_overall_status',
            field=models.CharField(blank=True, choices=[('Met', 'Met'), ('OnT', 'On Track'), ('NoP', 'No Progress'), ('Con', 'Constrained'), ('NoS', 'No Status')], max_length=3, null=True, verbose_name='Overall status set by UNICEF PO'),
        ),
    ]
