# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0006_auto_20181204_0013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportingperioddates',
            unique_together=set([('external_id', 'external_business_area_code', 'report_type', 'programme_document')]),
        ),
    ]
