# Generated by Django 1.11.20 on 2019-03-05 23:20
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import unicef.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0007_auto_20190311_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to=unicef.models.get_pr_attachment_upload_to)),
                ('type', models.CharField(choices=[('FACE', 'FACE'), ('Other', 'Other')], default='Other', max_length=5, verbose_name='Attachment type')),
                ('progress_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='unicef.ProgressReport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
