# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0007_auto_20170518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='reportable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.Reportable'),
        ),
    ]
