# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0007_auto_20171031_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerleveloutput',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
