# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0007_auto_20170519_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmedocument',
            name='cluster_leds',
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='reportable',
        ),
    ]
