# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 23:23
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.db import migrations


def forwards_func(apps, schema_editor):
    ProgressReport = apps.get_model("unicef", "ProgressReport")
    ProgressReportAttachment = apps.get_model("unicef", "ProgressReportAttachment")

    for item in ProgressReport.objects.all():
        try:
            ProgressReportAttachment.objects.create(
                progress_report=item,
                file=item.attachment,
                type="Other",
            )

        except ValueError:
            pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0008_progressreportattachment'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
