# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 23:23
from __future__ import unicode_literals

from django.core.files.base import ContentFile
from django.db import migrations


def forwards_func(apps, schema_editor):
    ProgressReport = apps.get_model("unicef", "ProgressReport")
    ProgressReportAttachment = apps.get_model("unicef", "ProgressReportAttachment")

    for item in ProgressReport.objects.all():
        try:
            new_file = ContentFile(item.attachment.read())
            new_file.name = item.attachment.name.split('/')[-1]
            new_file.path = f"unicef/progress_reports/{item.id}/{new_file.name}"

            ProgressReportAttachment.objects.create(
                progress_report=item,
                file=new_file,
            )

            item.attachment.delete()

        except ValueError:
            pass


def reverse_func(apps, schema_editor):
    ProgressReportAttachment = apps.get_model("unicef", "ProgressReportAttachment")

    for item in ProgressReportAttachment.objects.all():
        try:
            # Only do overwrite if ProgressReport's attachment field is None
            new_file = ContentFile(item.file.read())
            new_file.name = item.file.name.split('/')[-1]
            new_file.path = f"unicef/progress_reports/{new_file.name}"

            item.progress_report.attachment = new_file
            item.progress_report.save()

            item.file.delete()
        except ValueError:
            pass

    ProgressReportAttachment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0008_progressreportattachment'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
