# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0008_auto_20170523_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmedocument',
            name='contributing_to_cluser',
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='contributing_to_cluster',
            field=models.BooleanField(default=True, verbose_name='Contributing to Cluster'),
        ),
    ]
