# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0008_auto_20170718_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmedocument',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='progressreport',
            options={'ordering': ['-id']},
        ),
    ]
