# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0009_auto_20170816_2331'),
        ('unicef', '0009_auto_20170807_2147'),
    ]

    operations = [
    ]
