# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0009_auto_20170523_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='budget',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
