# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0009_auto_20170807_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=255, verbose_name='Phone Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='administrative_level',
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='response_to_HRP',
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=16, verbose_name='Organization acronym'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Organization name'),
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='partner_focal_point',
        ),
        migrations.RemoveField(
            model_name='programmedocument',
            name='unicef_focal_point',
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='unicef_officers',
            field=models.ManyToManyField(related_name='officer_programme_documents', to='unicef.Person', verbose_name='UNICEF Officer(s)'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='partner_focal_point',
            field=models.ManyToManyField(related_name='partner_focal_programme_documents', to='unicef.Person', verbose_name='Partner Focal Point(s)'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='unicef_focal_point',
            field=models.ManyToManyField(related_name='unicef_focal_programme_documents', to='unicef.Person', verbose_name='UNICEF Focal Point(s)'),
        ),
    ]
