# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0010_auto_20170831_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='budget_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', 'E')], default='USD', max_length=16, verbose_name='Budget Currency'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='cso_contribution_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', 'E')], default='USD', max_length=16, verbose_name='CSO Contribution Currency'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='in_kind_amount_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', 'E')], default='USD', max_length=16, verbose_name='UNICEF Supplies Currency'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='total_unicef_cash_currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', 'E')], default='USD', max_length=16, verbose_name='UNICEF cash Currency'),
        ),
    ]
