# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0010_programmedocument_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Budget', max_digits=12, null=True),
        ),
    ]
