# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0010_remove_progressreport_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreportattachment',
            name='type',
            field=models.CharField(choices=[('FACE', 'FACE'), ('Other', 'Other')], max_length=5, verbose_name='Attachment type'),
        ),
    ]
