# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0010_merge_20170817_1416'),
        ('unicef', '0011_auto_20170831_1204'),
    ]

    operations = [
    ]
