# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0011_remove_programmedocument_population_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='unicef/progress_reports/'),
        ),
    ]
