# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0011_auto_20170524_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SHP', 'Simplified Humanitarian Programme Document'), ('SSF', 'SSFA TOR')], default='PD', max_length=3, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='partner_focal_point',
            field=models.CharField(default='', max_length=255, verbose_name='Partner Focal Point(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='unicef_focal_point',
            field=models.CharField(default='', max_length=255, verbose_name='UNICEF Focal Point(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmedocument',
            name='unicef_office',
            field=models.CharField(default='', max_length=255, verbose_name='UNICEF Office(s)'),
            preserve_default=False,
        ),
    ]
