# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0011_auto_20170524_0824'),
        ('unicef', '0002_programmedocument_ref'),
    ]

    operations = [
    ]
