# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import unicef.models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0011_auto_20190418_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreportattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=unicef.models.get_pr_attachment_upload_to),
        ),
    ]
