# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0012_auto_20190507_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='funds_received_to_date_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='Funds received %'),
        ),
    ]
