# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0012_progressreport_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Is final report'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='report_number',
            field=models.IntegerField(default=1, verbose_name='Report Number'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='report_type',
            field=models.CharField(choices=[('QPR', 'Quarterly Progress Report'), ('HR', 'Humanitarian Report'), ('SR', 'Special Report')], default='QPR', max_length=3, verbose_name='Report type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together=set([('programme_document', 'report_type', 'report_number')]),
        ),
    ]
