# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0013_auto_20180212_2305'),
        ('unicef', '0013_auto_20180213_0824'),
    ]

    operations = [
    ]
