# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0013_auto_20180212_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperioddates',
            name='report_type',
            field=models.CharField(choices=[('QPR', 'Quarterly Progress Report'), ('HR', 'Humanitarian Report'), ('SR', 'Special Report')], default='QPR', max_length=3, verbose_name='Report type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportingperioddates',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='reportingperioddates',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
