# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0013_auto_20170524_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SHP', 'Simplified Humanitarian Programme Document'), ('SSF', 'SSFA TOR')], default='PD', max_length=3, verbose_name='Document Type'),
        ),
    ]
