# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0014_auto_20170524_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Ove', 'Over due'), ('Sub', 'Submitted'), ('Rej', 'Rejected')], default='Due', max_length=3),
        ),
    ]
