# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef', '0014_merge_20180214_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='submitting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted by / on behalf on'),
        ),
    ]
