# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 00:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0015_auto_20180215_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='amendments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
