# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0016_programmedocument_amendments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmedocument',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Budget', max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='cso_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='CSO Contribution'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='funds_received_to_date',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='Funds received'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='in_kind_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='UNICEF Supplies'),
        ),
        migrations.AlterField(
            model_name='programmedocument',
            name='total_unicef_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, verbose_name='UNICEF cash'),
        ),
    ]
