# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0016_auto_20191106_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdresultlink',
            options={'ordering': ['id'], 'verbose_name': 'Programme document result link'},
        ),
    ]
