# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0018_auto_20180419_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='narrative',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Narrative'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='challenges_in_the_reporting_period',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='partner_contribution_to_date',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='proposed_way_forward',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
