# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0019_auto_20180423_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperioddates',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
