# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0019_auto_20180423_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedocument',
            name='cluster_activity_indicator_id',
            field=models.CharField(blank=True, help_text='An ID representing ClusterActivity Reportable in PRP for dual reporting', max_length=32, null=True),
        ),
    ]
