# Generated by Django 2.2.16 on 2020-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0019_auto_20201118_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='financial_contribution_currency',
            field=models.CharField(choices=[('AED', 'aed'), ('AFN', 'afn'), ('ALL', 'all'), ('AMD', 'amd'), ('ANG', 'ang'), ('AOA', 'aoa'), ('ARS', 'ars'), ('AUD', 'aud'), ('AWG', 'awg'), ('AZN', 'azn'), ('BAM', 'bam'), ('BBD', 'bbd'), ('BDT', 'bdt'), ('BGN', 'bgn'), ('BHD', 'bhd'), ('BIF', 'bif'), ('BMD', 'bmd'), ('BND', 'bnd'), ('BOB', 'bob'), ('BRL', 'brl'), ('BSD', 'bsd'), ('BTN', 'btn'), ('BWP', 'bwp'), ('BYN', 'byn'), ('BZD', 'bzd'), ('CAD', 'cad'), ('CDF', 'cdf'), ('CHF', 'chf'), ('CLP', 'clp'), ('CNY', 'cny'), ('COP', 'cop'), ('CRC', 'crc'), ('CUC', 'cuc'), ('CUP', 'cup'), ('CVE', 'cve'), ('CZK', 'czk'), ('DJF', 'djf'), ('DKK', 'dkk'), ('DOP', 'dop'), ('DZD', 'dzd'), ('EGP', 'egp'), ('ERN', 'ern'), ('ETB', 'etb'), ('EUR', '€'), ('FJD', 'fjd'), ('FKP', 'fkp'), ('GBP', 'gbp'), ('GEL', 'gel'), ('GGP', 'ggp'), ('GHS', 'ghs'), ('GIP', 'gip'), ('GMD', 'gmd'), ('GNF', 'gnf'), ('GTQ', 'gtq'), ('GYD', 'gyd'), ('HKD', 'hkd'), ('HNL', 'hnl'), ('HRK', 'hrk'), ('HTG', 'htg'), ('HUF', 'huf'), ('IDR', 'idr'), ('ILS', 'ils'), ('IMP', 'imp'), ('INR', 'inr'), ('IQD', 'iqd'), ('IRR', 'irr'), ('ISK', 'isk'), ('JEP', 'jep'), ('JMD', 'jmd'), ('JOD', 'jod'), ('JPY', 'jpy'), ('KES', 'kes'), ('KGS', 'kgs'), ('KHR', 'khr'), ('KMF', 'kmf'), ('KPW', 'kpw'), ('KRW', 'krw'), ('KWD', 'kwd'), ('KYD', 'kyd'), ('KZT', 'kzt'), ('LAK', 'lak'), ('LBP', 'lbp'), ('LKR', 'lkr'), ('LRD', 'lrd'), ('LSL', 'lsl'), ('LYD', 'lyd'), ('MAD', 'mad'), ('MDL', 'mdl'), ('MGA', 'mga'), ('MKD', 'mkd'), ('MMK', 'mmk'), ('MNT', 'mnt'), ('MOP', 'mop'), ('MRO', 'mro'), ('MUR', 'mur'), ('MVR', 'mvr'), ('MWK', 'mwk'), ('MXN', 'mxn'), ('MYR', 'myr'), ('MZN', 'mzn'), ('NAD', 'nad'), ('NGN', 'ngn'), ('NIO', 'nio'), ('NOK', 'nok'), ('NPR', 'npr'), ('NZD', 'nzd'), ('OMR', 'omr'), ('PAB', 'pab'), ('PEN', 'pen'), ('PGK', 'pgk'), ('PHP', 'php'), ('PKR', 'pkr'), ('PLN', 'pln'), ('PYG', 'pyg'), ('QAR', 'qar'), ('RON', 'ron'), ('RSD', 'rsd'), ('RUB', 'rub'), ('RWF', 'rwf'), ('SAR', 'sar'), ('SBD', 'sbd'), ('SCR', 'scr'), ('SDG', 'sdg'), ('SEK', 'sek'), ('SGD', 'sgd'), ('SHP', 'shp'), ('SLL', 'sll'), ('SOS', 'sos'), ('SPL', 'spl'), ('SRD', 'srd'), ('STD', 'std'), ('SVC', 'svc'), ('SYP', 'syp'), ('SZL', 'szl'), ('THB', 'thb'), ('TJS', 'tjs'), ('TMT', 'tmt'), ('TND', 'tnd'), ('TOP', 'top'), ('TRY', 'try'), ('TTD', 'ttd'), ('TVD', 'tvd'), ('TWD', 'twd'), ('TZS', 'tzs'), ('UAH', 'uah'), ('UGX', 'ugx'), ('USD', '$'), ('UYU', 'uyu'), ('UZS', 'uzs'), ('VEF', 'vef'), ('VND', 'vnd'), ('VUV', 'vuv'), ('WST', 'wst'), ('XAF', 'xaf'), ('XCD', 'xcd'), ('XDR', 'xdr'), ('XOF', 'xof'), ('XPF', 'xpf'), ('YER', 'yer'), ('YER1', 'yer1'), ('ZAR', 'zar'), ('ZMW', 'zmw'), ('ZWD', 'zwd'), ('ZWL', 'zwl'), ('SSP', 'ssp')], default='USD', max_length=16, verbose_name='Financial Contribution Currency'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='financial_contribution_to_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
