# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0020_reportingperioddates_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_email',
            field=models.CharField(default='not_available@example.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_external_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressreport',
            name='reviewed_by_name',
            field=models.CharField(default='Not Available', max_length=256),
            preserve_default=False,
        ),
    ]
