# Generated by Django 1.11.20 on 2019-03-07 23:13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportablelocationgoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
