# Generated by Django 1.11.20 on 2019-05-07 19:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_reportablelocationgoal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorreport',
            name='narrative_assessment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
