# Generated by Django 3.2.6 on 2021-11-05 00:14

from django.db import migrations, models
import etools_prp.apps.indicator.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20200520_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorlocationdata',
            name='disaggregation',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_disaggregation),
        ),
    ]
