# Generated by Django 3.2.6 on 2021-09-07 19:40

import django.contrib.postgres.fields
from django.db import migrations, models
import etools_prp.apps.indicator.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20200520_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorlocationdata',
            name='disaggregation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='total',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_total),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='baseline',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='in_need',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='location_admin_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='target',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='total',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_total),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='baseline',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='in_need',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='target',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value),
        ),
    ]
