# Generated by Django 3.2.6 on 2022-03-16 15:39

import django.contrib.postgres.fields
from django.db import migrations, models
import etools_prp.apps.core.encoders
import etools_prp.apps.indicator.models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_alter_indicatorlocationdata_disaggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorlocationdata',
            name='disaggregation',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_disaggregation, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='total',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_total, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='baseline',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='in_need',
            field=models.JSONField(blank=True, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='location_admin_refs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(encoder=etools_prp.apps.core.encoders.CustomJSONEncoder), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='target',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='total',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_total, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='baseline',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='in_need',
            field=models.JSONField(blank=True, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='reportablelocationgoal',
            name='target',
            field=models.JSONField(default=etools_prp.apps.indicator.models.default_value, encoder=etools_prp.apps.core.encoders.CustomJSONEncoder),
        ),
    ]
