# Generated by Django 3.2.6 on 2022-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_auto_20220725_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_locations',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('latest', 'latest')], default='sum', max_length=10),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='calculation_formula_across_periods',
            field=models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('latest', 'latest')], default='sum', max_length=10),
        ),
    ]
