# Generated by Django 3.2.6 on 2025-06-05 06:57

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20220822_1007'),
        ('unicef', '0031_auto_20250605_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregation',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='gpd_progress_report',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='indicator_reports',
                to='unicef.gpdprogressreport'
            ),
        ),
    ]
