# Generated by Django 3.2.15 on 2025-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20220822_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregation',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='reportable',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
    ]
