# Generated by Django 3.2.6 on 2025-06-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unicef', '0031_auto_20250605_1017'),
        ('indicator', '0012_auto_20250605_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='gpd_progress_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='unicef.gpdprogressreport'),
        ),
    ]
