# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
        ('core', '0001_initial'),
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('baseline', models.FloatField()),
                ('target', models.FloatField()),
                ('in_need', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('report_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_blueprints', to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorDataSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calculation_method', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_specifications', to='reporting.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorDisaggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('range', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_disaggregations', to='reporting.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('in_ops', models.BooleanField(default=False)),
                ('geograph', models.CharField(max_length=255)),
                ('time_period', models.DateTimeField(auto_now=True)),
                ('budget', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cluster.Cluster')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participant_donors', to=settings.AUTH_USER_MODEL)),
                ('implementing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participant_implementing_partners', to='core.Partner')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participant_owners', to=settings.AUTH_USER_MODEL)),
                ('report_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participant_report_agencies', to='core.Partner')),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='reporting.Project'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='reporting.Project'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reporting.IndicatorBlueprint'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='cluster.ClusterObjective'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reporting.Project'),
        ),
    ]
