# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cluster', '0003_clusteractivity'),
        ('analytics', '0003_auto_20170419_2023'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProgrammeOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LowerLevelOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll_outputs', to='reporting.CountryProgrammeOutput')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('baseline', models.FloatField()),
                ('target', models.FloatField()),
                ('in_need', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('report_description', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='indicatorblueprint',
            name='activity',
        ),
        migrations.AddField(
            model_name='indicatorblueprint',
            name='cluster_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_blueprints', to='cluster.ClusterActivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatordataspecification',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data_specifications', to='reporting.Reportable'),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregation',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_disaggregations', to='reporting.Reportable'),
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.AddField(
            model_name='reportable',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='reporting.IndicatorBlueprint'),
        ),
        migrations.AddField(
            model_name='reportable',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='reportable',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='cluster.ClusterObjective'),
        ),
        migrations.AddField(
            model_name='reportable',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportables', to='reporting.Project'),
        ),
        migrations.AddField(
            model_name='countryprogrammeoutput',
            name='programme_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_outputs', to='reporting.ProgrammeDocument'),
        ),
    ]
