# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170509_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='parent_indicator',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reporting.Reportable'),
        ),
    ]
