# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20170509_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportable',
            name='parent_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reporting.Reportable'),
        ),
    ]
