# Generated by Django 1.11.11 on 2018-10-24 00:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180905_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseplan',
            name='plan_custom_type_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plan Custom Type Label'),
        ),
        migrations.AlterField(
            model_name='responseplan',
            name='plan_type',
            field=models.CharField(choices=[('HRP', 'HRP'), ('FA', 'FA'), ('OTHER', 'Other')], default='HRP', max_length=5, verbose_name='Plan Type'),
        ),
    ]
