# Generated by Django 2.2.12 on 2020-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200520_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ISO3 Code'),
        ),
    ]
