# Generated by Django 3.2.6 on 2022-01-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_country_iso3_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'p_code')},
        ),
    ]
