# Generated by Django 3.2.6 on 2022-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220104_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatewaytype',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='p_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='P Code'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'gateway', 'p_code')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='carto_db_table',
        ),
    ]
