# Generated by Django 3.2.6 on 2022-01-26 21:14

from django.db import migrations

def migrate_workspace(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    CartoDBTable = apps.get_model("core", "CartoDBTable")

    for loc in Location.objects.all():
        workspaces = loc.gateway.country.workspaces.count()
        print(workspaces)
        assert workspaces == 1
        loc.workspaces.set(loc.gateway.country.workspaces.all())
        loc.admin_level_name = loc.gateway.name
        loc.admin_level = loc.gateway.admin_level
        loc.save()

    for table in CartoDBTable.objects.all():
        table.admin_level_name = table.location_type.name
        table.admin_level = table.location_type.admin_level
        table.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220126_2114'),
    ]

    operations = [
        migrations.RunPython(migrate_workspace, migrations.RunPython.noop)
    ]
