# Generated by Django 3.2.6 on 2022-01-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220126_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'p_code')},
        ),
        migrations.RemoveField(
            model_name='location',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cartodbtable',
            name='location_type',
        ),
    ]
