# Generated by Django 3.2.6 on 2022-02-04 18:32

from django.db import migrations, models
import django.utils.timezone
import etools_prp.apps.core.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220126_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartodbtable',
            name='api_key',
            field=models.CharField(default='-', max_length=254, verbose_name='API Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='color',
            field=models.CharField(blank=True, default=etools_prp.apps.core.models.get_random_color, max_length=7, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='cartodbtable',
            name='remap_table_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Remap Table Name'),
        ),
    ]
