# Generated by Django 3.2.6 on 2022-02-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220204_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='admin_level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Admin Level'),
        ),
        migrations.AlterField(
            model_name='location',
            name='admin_level_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Admin Level Name'),
        ),
    ]
