# Generated by Django 3.2.6 on 2022-02-23 23:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_location_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='countries',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Point'),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        ),
    ]
