# Generated by Django 3.2.6 on 2022-03-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220223_2323'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='CartoDBTable'),
            ],
            database_operations=[
            ]
        )
    ]
