# Generated by Django 3.2.6 on 2025-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_prprole_prproleold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='prproleold',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='responseplan',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='external_source',
            field=models.TextField(blank=True, choices=[('HPC', 'HPC'), ('OPS', 'OPS'), ('UNICEF', 'UNICEF'), ('ETOOLS', 'ETOOLS')], null=True),
        ),
    ]
