# Generated by Django 3.2.15 on 2025-11-21 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_auto_20250623_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_count', models.IntegerField(help_text='Number of records affected')),
                ('model_name', models.CharField(help_text='Name of the model that was bulk modified', max_length=100)),
                ('app_label', models.CharField(help_text='App label of the model', max_length=100)),
                ('affected_ids', models.JSONField(default=list, help_text='List of IDs of the records that were affected')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the bulk action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Action Log',
                'verbose_name_plural': 'Bulk Action Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
