# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='reporting.Indicator'),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='core.Location'),
        ),
    ]
