# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170419_2023'),
        ('analytics', '0003_auto_20170419_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='reportable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='reporting.Reportable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='time_period',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_report', to='core.Location'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='progress_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_report', to='analytics.IndicatorReport'),
        ),
    ]
