# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 16:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20170419_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='disaggregation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='is_disaggregated_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='report_status',
            field=models.CharField(choices=[('OT', 'On Track'), ('Con', 'Constrained'), ('NP', 'No Progress'), ('TM', 'Target Met')], default='OT', max_length=3),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
