FROM mhart/alpine-node:11.13.0 as builder

RUN apk update
RUN apk --update --no-cache \
		add  \
    automake \
		git \
		alpine-sdk  \
		nasm  \
		autoconf  \
		build-base \
		zlib \
		zlib-dev \
		libpng \
		libpng-dev\
		libwebp \
		libwebp-dev \
		libjpeg-turbo \
		libjpeg-turbo-dev

RUN npm install -g bower@~1.7.0 polymer-cli gulp-cli --unsafe-perm

ADD bower.json /tmp/
ADD package.json /tmp/

WORKDIR /tmp

RUN npm install
RUN bower --allow-root install

ADD . /code/
RUN cp -a /tmp/node_modules /code/node_modules
RUN cp -a /tmp/bower_components /code/bower_components

WORKDIR /code

RUN npm run bundle


FROM mhart/alpine-node:11.13.0

RUN apk update
RUN apk add --update bash

WORKDIR /code
RUN npm install express --no-save
RUN npm install browser-capabilities@1.1.3 --no-save
COPY --from=builder /code/express.js /code/express.js
COPY --from=builder /code/build /code/build
EXPOSE 8082
CMD ["node", "express.js"]
